import { NextRequest,NextResponse } from 'next/server'
import { authorizeCompetitionSeries } from '@/features/competition/series/competition-series.auth'
import { readSeriesJson,seriesErrorResponse } from '@/features/competition/series/competition-series.http'
import { assertSeriesDivision,getSeriesRevision,rpc } from '@/features/competition/series/competition-series.repository'
import { isUuid,validateDivision } from '@/features/competition/series/competition-series.validation'
type Context={params:Promise<{clubId:string;seriesId:string}>}
export async function GET(req:NextRequest,context:Context){const {clubId,seriesId}=await context.params;if(!isUuid(clubId)||!isUuid(seriesId))return NextResponse.json({error:'Identificador inválido.'},{status:400});const auth=await authorizeCompetitionSeries(req,clubId,'read');if(auth.error||!auth.client)return auth.error;const {data,error}=await auth.client.from('competition_series_divisions').select('*').eq('club_id',clubId).eq('series_id',seriesId).order('sort_order');if(error)return seriesErrorResponse(Object.assign(new Error(error.message),{code:error.code}));return NextResponse.json({divisions:data??[]})}
export async function POST(req:NextRequest,context:Context){const {clubId,seriesId}=await context.params;if(!isUuid(clubId)||!isUuid(seriesId))return NextResponse.json({error:'Identificador inválido.'},{status:400});const auth=await authorizeCompetitionSeries(req,clubId,'write');if(auth.error||!auth.client)return auth.error;const body=await readSeriesJson(req);if('error'in body)return body.error;const validation=validateDivision(body.value);if('error'in validation||!validation.value.divisionId)return NextResponse.json({error:'error'in validation?validation.error:'División inválida.'},{status:400});try{const division=await rpc(auth.client,'add_competition_series_division',{p_club_id:clubId,p_series_id:seriesId,p_division_id:validation.value.divisionId,p_sort_order:validation.value.sortOrder,p_series_revision:validation.value.revision});return NextResponse.json({ok:true,division,revision:await getSeriesRevision(auth.client,clubId,seriesId)},{status:201})}catch(error){return seriesErrorResponse(error)}}
export async function PATCH(req:NextRequest,context:Context){const {clubId,seriesId}=await context.params;if(!isUuid(clubId)||!isUuid(seriesId))return NextResponse.json({error:'Identificador inválido.'},{status:400});const auth=await authorizeCompetitionSeries(req,clubId,'write');if(auth.error||!auth.client)return auth.error;const body=await readSeriesJson(req);if('error'in body)return body.error;const validation=validateDivision(body.value);if('error'in validation||!validation.value.linkId)return NextResponse.json({error:'error'in validation?validation.error:'Relación inválida.'},{status:400});try{await assertSeriesDivision(auth.client,clubId,seriesId,validation.value.linkId);const division=await rpc(auth.client,'remove_competition_series_division',{p_club_id:clubId,p_series_division_id:validation.value.linkId,p_series_revision:validation.value.revision});return NextResponse.json({ok:true,division,revision:await getSeriesRevision(auth.client,clubId,seriesId)})}catch(error){return seriesErrorResponse(error)}}
