import{NextRequest,NextResponse}from'next/server'
import{authorizeCompetitionHomologation}from'./competition-homologation.auth'
import{homologationError,readJson}from'./competition-homologation.http'
import{getHomologationDetail,homologationRpc,listHomologations}from'./competition-homologation.repository'
import{toHomologationAdminDto}from'./competition-homologation.mapper'
import{isUuid,parseKey,parseRevision,record,text}from'./competition-homologation.validation'
type Params={clubId:string;seriesId:string;eventId:string;eventDivisionId:string;homologationId?:string}
const invalid=()=>NextResponse.json({error:'Identificador inválido.'},{status:400})
async function scope(request:NextRequest,p:Params,mode:'read'|'write'){if(![p.clubId,p.seriesId,p.eventId,p.eventDivisionId].every(isUuid)||p.homologationId&&!isUuid(p.homologationId))return{error:invalid(),client:null};const auth=await authorizeCompetitionHomologation(request,p.clubId,mode);if(auth.error||!auth.client)return auth;const division=await auth.client.from('competition_series_event_divisions').select('id,competition_series_events!inner(id,series_id)').eq('club_id',p.clubId).eq('id',p.eventDivisionId).eq('event_id',p.eventId).eq('competition_series_events.series_id',p.seriesId).maybeSingle();if(division.error)throw Object.assign(new Error(division.error.message),{code:division.error.code});if(!division.data)return{...auth,client:null,error:NextResponse.json({error:'Recurso inexistente.'},{status:404})};return auth}
function command(request:NextRequest){const revision=parseRevision(request.headers.get('if-match')),key=parseKey(request.headers.get('idempotency-key'));return revision&&key?{revision,key}:{error:NextResponse.json({error:'If-Match e Idempotency-Key son obligatorios.'},{status:400})}}
export async function homologationsCollection(request:NextRequest,p:Params){try{const auth=await scope(request,p,request.method==='GET'?'read':'write');if(auth.error||!auth.client)return auth.error;if(request.method==='GET')return NextResponse.json({homologations:await listHomologations(auth.client,p.clubId,p.eventDivisionId)});const body=await readJson(request);if('error'in body)return body.error;const draft=await homologationRpc<Record<string,unknown>>(auth.client,'create_competition_event_homologation_draft',{p_club_id:p.clubId,p_event_division_id:p.eventDivisionId,p_notes:text(record(body.value).notes)||null});return NextResponse.json({homologation:draft},{status:201})}catch(error){return homologationError(error)}}
export async function homologationDetail(request:NextRequest,p:Params){try{const auth=await scope(request,p,'read');if(auth.error||!auth.client||!p.homologationId)return auth.error??invalid();return NextResponse.json(toHomologationAdminDto(await getHomologationDetail(auth.client,p.clubId,p.homologationId)))}catch(error){return homologationError(error)}}
export async function homologationPreflight(request:NextRequest,p:Params){try{const auth=await scope(request,p,'read');if(auth.error||!auth.client||!p.homologationId)return auth.error??invalid();return NextResponse.json(await homologationRpc(auth.client,'get_competition_event_homologation_preflight',{p_club_id:p.clubId,p_homologation_id:p.homologationId}))}catch(error){return homologationError(error)}}
export async function homologationCommand(request:NextRequest,p:Params,operation:'extract'|'submit'|'approve'|'reject'|'correction'|'supersede'){try{const auth=await scope(request,p,'write');if(auth.error||!auth.client||!p.homologationId)return auth.error??invalid();const concurrency=command(request);if('error'in concurrency)return concurrency.error;const bodyResult=await readJson(request);if('error'in bodyResult)return bodyResult.error;const body=record(bodyResult.value);let result:unknown
    if(operation==='extract')result=await homologationRpc(auth.client,'extract_competition_event_homologation_results',{p_club_id:p.clubId,p_homologation_id:p.homologationId,p_revision:concurrency.revision,p_idempotency_key:concurrency.key})
    else if(operation==='correction')result=await homologationRpc(auth.client,'create_competition_event_homologation_correction',{p_club_id:p.clubId,p_homologation_id:p.homologationId,p_revision:concurrency.revision,p_idempotency_key:concurrency.key,p_notes:text(body.notes)||null})
    else{const args:Record<string,unknown>={p_club_id:p.clubId,p_homologation_id:p.homologationId,p_revision:concurrency.revision,p_idempotency_key:concurrency.key};if(operation==='reject'||operation==='supersede')args.p_reason=text(body.reason);result=await homologationRpc(auth.client,`${operation}_competition_event_homologation`,args)}
    return NextResponse.json({ok:true,result})}catch(error){return homologationError(error)}}
export async function homologationEvidence(request:NextRequest,p:Params){try{const auth=await scope(request,p,'write');if(auth.error||!auth.client||!p.homologationId)return auth.error??invalid();const revision=parseRevision(request.headers.get('if-match'));if(!revision)return NextResponse.json({error:'If-Match es obligatorio.'},{status:400});const bodyResult=await readJson(request);if('error'in bodyResult)return bodyResult.error;const body=record(bodyResult.value);const result=await homologationRpc(auth.client,'add_competition_event_homologation_evidence',{p_club_id:p.clubId,p_homologation_id:p.homologationId,p_revision:revision,p_evidence_type:text(body.evidence_type),p_storage_path:text(body.storage_path)||null,p_external_url:text(body.external_url)||null,p_description:text(body.description)||null,p_checksum:text(body.checksum)||null,p_metadata:record(body.metadata)});return NextResponse.json({ok:true,result},{status:201})}catch(error){return homologationError(error)}}
