'use client'

import Link from 'next/link'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertCircle, ArrowLeft, Check, CircleAlert, FileCheck2, LoaderCircle, RefreshCw, ShieldCheck, X } from 'lucide-react'
import { useSession } from '@/components/session/SessionProvider'
import { supabase } from '@/lib/supabaseClient'
import type { Homologation } from '@/features/competition/homologation/competition-homologation.types'
import styles from './EventHomologationAdmin.module.css'

type Row = Record<string, unknown>
type Detail = { homologation: Homologation; event_division: Row; tournament: Row; participants: Row[]; results: Row[]; issues: Row[]; blockers: Row[]; warnings: Row[]; evidence: Row[]; allowed_actions: Record<string, boolean> }
type ApiError = Error & { status?: number }
const statusLabel: Record<string, string> = { DRAFT: 'Borrador', SUBMITTED: 'Enviada', APPROVED: 'Aprobada', REJECTED: 'Rechazada', SUPERSEDED: 'Reemplazada' }
const actionLabel: Record<string, string> = { extract: 'Preparar resultados', submit: 'Enviar a revisión', approve: 'Aprobar', correction: 'Crear corrección', supersede: 'Reemplazar' }
async function token() { return (await supabase.auth.getSession()).data.session?.access_token ?? '' }
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, cache: 'no-store', headers: { Authorization: `Bearer ${await token()}`, 'Content-Type': 'application/json', ...init?.headers } }); const body = await response.json().catch(() => ({})) as T & { error?: string }; if (!response.ok) throw Object.assign(new Error(response.status >= 500 ? 'No pudimos completar la operación.' : body.error || 'No pudimos completar la operación.'), { status: response.status }); return body }
function value(row: Row, keys: string[], fallback = 'Sin datos') { for (const key of keys) if (typeof row[key] === 'string' || typeof row[key] === 'number') return String(row[key]); return fallback }
function issueText(row: Row) { return value(row, ['message', 'detail', 'description', 'code'], 'Revisá esta condición.') }
function participantName(row: Row) { const snapshot = row.participant_snapshot as Row | undefined; return value(row, ['display_name', 'pair_name', 'entry_name'], value(snapshot ?? {}, ['display_name', 'pair_name', 'name'], 'Participante')) }
function resultName(row: Row) { const position = Number(row.final_position ?? 0); return position === 1 ? 'Campeón' : position === 2 ? 'Finalista' : position <= 4 ? 'Semifinalista' : position <= 8 ? 'Cuartos' : 'Participante' }

export default function EventHomologationAdmin({ seriesId, eventId, eventDivisionId }: { seriesId: string; eventId: string; eventDivisionId: string }) {
  const { activeClub } = useSession(); const clubId = activeClub?.id
  const [detail, setDetail] = useState<Detail | null>(null), [loading, setLoading] = useState(true), [fatal, setFatal] = useState(false), [busy, setBusy] = useState(''), [error, setError] = useState<ApiError | null>(null), [notice, setNotice] = useState(''), [reason, setReason] = useState(''), [evidenceOpen, setEvidenceOpen] = useState(false)
  const collection = clubId ? `/api/clubs/${clubId}/competition/series/${seriesId}/events/${eventId}/divisions/${eventDivisionId}/homologations` : ''
  const load = useCallback(async () => { if (!clubId) return; setLoading(true); setFatal(false); setError(null); try { const list = await api<{ homologations: Homologation[] }>(collection); if (!list.homologations.length) setDetail(null); else setDetail(await api<Detail>(`${collection}/${list.homologations[0].id}`)) } catch (cause) { setFatal(true); setError(cause as ApiError) } finally { setLoading(false) } }, [clubId, collection])
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer) }, [load])
  async function createDraft() { setBusy('create'); setError(null); try { const created = await api<{ homologation: Homologation }>(collection, { method: 'POST', body: JSON.stringify({ notes: 'Preparada desde administración.' }) }); await api(`${collection}/${created.homologation.id}/extract`, { method: 'POST', headers: { 'If-Match': String(created.homologation.revision), 'Idempotency-Key': crypto.randomUUID() }, body: '{}' }); setNotice('Participantes y resultados detectados.'); await load() } catch (cause) { setError(cause as ApiError) } finally { setBusy('') } }
  async function command(operation: string) { if (!detail) return; setBusy(operation); setNotice(''); setError(null); try { await api(`${collection}/${detail.homologation.id}/${operation}`, { method: 'POST', headers: { 'If-Match': String(detail.homologation.revision), 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify(operation === 'reject' || operation === 'supersede' ? { reason } : operation === 'correction' ? { notes: reason || null } : {}) }); setReason(''); setNotice('Operación completada.'); await load() } catch (cause) { const next = cause as ApiError; setError(next); if (next.status === 412) await load() } finally { setBusy('') } }
  const preflight = useMemo(() => detail ? [...detail.blockers.map(item => ({ kind: 'blocker', item })), ...detail.warnings.map(item => ({ kind: 'warning', item }))] : [], [detail])
  const back = `/club/competition/series/${seriesId}/events/${eventId}`
  if (!clubId) return <main className={styles.page}><div className={styles.state}>Seleccioná un club.</div></main>
  if (loading) return <main className={styles.page}><div className={styles.skeleton}><LoaderCircle />Cargando homologación…</div></main>
  if (error && fatal && !detail) { const message = error.status === 401 ? 'Volvé a iniciar sesión.' : error.status === 403 ? 'Tu rol no puede acceder a la homologación.' : error.status === 404 ? 'La división ya no existe.' : error.status === 409 ? 'El estado actual no permite esta operación.' : error.status === 412 ? 'La revisión cambió. Recargamos los datos.' : error.message; return <main className={styles.page}><div className={styles.state}><CircleAlert /><strong>No pudimos abrir la homologación</strong><p>{message}</p><button onClick={() => void load()}><RefreshCw size={16} />Reintentar</button></div></main> }
  if (!detail) return <main className={styles.page}><header className={styles.hero}><Link href={back}><ArrowLeft size={18} /></Link><div><span>HOMOLOGACIÓN</span><h1>Preparar resultados</h1><p>La división todavía no tiene una homologación.</p></div></header>{error ? <p className={styles.error}><AlertCircle size={15} />{error.status === 409 ? 'Completá las precondiciones del evento antes de preparar la homologación.' : error.message}</p> : null}<div className={styles.empty}><FileCheck2 /><strong>Sin homologación</strong><p>Prepará un borrador para detectar participantes y resultados del torneo vinculado.</p><button disabled={busy === 'create'} onClick={() => void createDraft()}>{busy ? 'Preparando…' : 'Preparar homologación'}</button></div></main>
  const h = detail.homologation
  return <main className={styles.page}><header className={styles.hero}><div className={styles.heroTop}><Link href={back} aria-label="Volver"><ArrowLeft size={18} /></Link><span>HOMOLOGACIÓN</span><b className={`${styles.badge} ${styles[`status_${h.status}`]}`}>{statusLabel[h.status]}</b></div><div className={styles.heading}><div><h1>{value(detail.tournament, ['name'], 'Torneo')}</h1><p>Versión {h.version} · Revisión {h.revision}</p></div><ShieldCheck size={25} /></div><div className={styles.meta}><span>{new Date(h.created_at).toLocaleDateString('es-AR')}</span><span>{h.submitted_by ? 'Enviada por un administrador' : 'Creada por un administrador'}</span></div></header>
    {error ? <p className={styles.error}><AlertCircle size={15} />{error.status === 412 ? 'Los datos cambiaron y fueron recargados.' : error.message}</p> : null}{notice ? <p className={styles.success}><Check size={15} />{notice}</p> : null}
    <section className={styles.summary}><div><strong>{detail.participants.length}</strong><small>Participantes</small></div><div><strong>{detail.results.length}</strong><small>Resultados</small></div><div><strong>{detail.issues.length}</strong><small>Problemas</small></div></section>
    <details open className={styles.section}><summary>Participantes <span>{detail.participants.length}</span></summary><div className={styles.rows}>{!detail.participants.length ? <p className={styles.muted}>Todavía no se detectaron participantes.</p> : detail.participants.map((row, index) => <article key={value(row, ['id'], String(index))}><div><strong>{participantName(row)}</strong><small>{value(row, ['entry_type', 'participant_type'], 'Entry')} · {row.is_eligible === false ? 'No elegible' : 'Elegible'}</small></div><span className={styles.chip}>{value(row, ['status'], row.is_eligible === false ? 'Revisar' : 'OK')}</span></article>)}</div></details>
    <details className={styles.section}><summary>Resultados detectados <span>{detail.results.length}</span></summary><div className={styles.results}>{!detail.results.length ? <p className={styles.muted}>Prepará los resultados para ver posiciones.</p> : detail.results.map((row, index) => <div key={value(row, ['id'], String(index))}><b>#{value(row, ['final_position'], '—')}</b><span><strong>{resultName(row)}</strong><small>{participantName(row)}</small></span></div>)}</div></details>
    <details className={styles.section}><summary>Preflight <span>{preflight.length}</span></summary><div className={styles.preflight}>{!preflight.length ? <p className={styles.ok}><Check size={15} />Sin bloqueos ni advertencias.</p> : preflight.map(({ kind, item }, index) => <p className={kind === 'blocker' ? styles.blocker : styles.warning} key={`${kind}-${index}`}>{kind === 'blocker' ? <X size={15} /> : <AlertCircle size={15} />}{issueText(item)}</p>)}{detail.issues.map((item, index) => <p className={styles.warning} key={`issue-${index}`}><AlertCircle size={15} />{issueText(item)}</p>)}</div></details>
    <details className={styles.section}><summary>Evidencia <span>{detail.evidence.length}</span></summary><div className={styles.evidence}>{!detail.evidence.length ? <p className={styles.muted}>No hay archivos o enlaces adjuntos.</p> : detail.evidence.map((row, index) => <a href={value(row, ['external_url'], '#')} key={value(row, ['id'], String(index))} target="_blank" rel="noreferrer"><FileCheck2 size={16} /><span><strong>{value(row, ['description', 'evidence_type'], 'Evidencia')}</strong><small>{value(row, ['uploaded_at'], '')}</small></span></a>)}<button onClick={() => setEvidenceOpen(true)}>Agregar evidencia</button>{evidenceOpen ? <p className={styles.muted}>El cargador de evidencia estará disponible cuando exista un uploader reutilizable.</p> : null}</div></details>
    <section className={styles.actions}><h2>Acciones</h2><div>{Object.entries(actionLabel).filter(([key]) => detail.allowed_actions[key]).map(([key, label]) => <button disabled={Boolean(busy)} key={key} onClick={() => void command(key)}>{busy === key ? 'Procesando…' : label}</button>)}</div>{detail.allowed_actions.reject || detail.allowed_actions.supersede || detail.allowed_actions.correction ? <label>Motivo o nota<input value={reason} onChange={event => setReason(event.target.value)} placeholder="Explicá el cambio" /></label> : null}{detail.allowed_actions.reject ? <button className={styles.danger} disabled={!reason.trim() || Boolean(busy)} onClick={() => void command('reject')}>Rechazar</button> : null}</section>
  </main>
}
