'use client'

import { useEffect, useState } from 'react'
import { Gift, Plus, Trash2 } from 'lucide-react'
import { ActionFeedbackNotice, type ActionFeedbackTone } from '@/components/ui/ActionFeedbackNotice'
import type { CompetitionSeriesPrize, CompetitionSeriesPrizeType } from '@/features/competition/series/competition-series.types'
import styles from './SeriesPrizesPanel.module.css'

type Request = <T>(url:string,init?:RequestInit)=>Promise<T>
type Draft = { id:string; positionFrom:string; positionTo:string; title:string; description:string; prizeType:CompetitionSeriesPrizeType; amount:string; currencyCode:string }
const typeLabels:Record<CompetitionSeriesPrizeType,string>={CASH:'Dinero',GOODS:'Producto',SERVICE:'Servicio',TROPHY:'Trofeo',OTHER:'Otro'}
const position=(from:number,to:number)=>from===1&&to===1?'Campeón':from===2&&to===2?'Finalista':from===3&&to===4?'Semifinalistas':from===to?`Puesto ${from}`:`Puestos ${from}–${to}`
const displayAmount=(item:CompetitionSeriesPrize)=>item.prize_type==='CASH'&&item.amount!==null?new Intl.NumberFormat('es-AR',{style:'currency',currency:item.currency_code||'ARS',maximumFractionDigits:0}).format(Number(item.amount)):null

export default function SeriesPrizesPanel({clubId,seriesId,seriesRevision,editable,request,reload}:{clubId:string;seriesId:string;seriesRevision:number;editable:boolean;request:Request;reload:()=>Promise<void>}){
  const [items,setItems]=useState<CompetitionSeriesPrize[]>([])
  const [drafts,setDrafts]=useState<Draft[]>([])
  const [editing,setEditing]=useState(false)
  const [saving,setSaving]=useState(false)
  const [feedback,setFeedback]=useState<{tone:ActionFeedbackTone;title:string;message:string}|null>(null)
  useEffect(()=>{let active=true;void request<{prizes:CompetitionSeriesPrize[]}>(`/api/clubs/${clubId}/competition/series/${seriesId}/prizes`).then(({prizes})=>{if(active)setItems(prizes)}).catch(()=>{if(active)setFeedback({tone:'error',title:'No pudimos cargar los premios',message:'Actualizá la pantalla e intentá nuevamente.'})});return()=>{active=false}},[clubId,request,seriesId])
  function begin(){setDrafts(items.map((item)=>({id:item.id,positionFrom:String(item.position_from),positionTo:String(item.position_to),title:item.title,description:item.description||'',prizeType:item.prize_type,amount:item.amount===null?'':String(item.amount),currencyCode:item.currency_code||'ARS'})));setEditing(true);setFeedback(null)}
  function add(){setEditing(true);setDrafts((current)=>[...current,{id:crypto.randomUUID(),positionFrom:'1',positionTo:'1',title:'Campeón',description:'',prizeType:'TROPHY',amount:'',currencyCode:'ARS'}])}
  function patch(id:string,value:Partial<Draft>){setDrafts((current)=>current.map((item)=>item.id===id?{...item,...value}:item))}
  async function save(){setSaving(true);setFeedback(null);try{const payload=drafts.map((item,index)=>({position_from:Number(item.positionFrom),position_to:Number(item.positionTo),title:item.title.trim(),description:item.description.trim()||null,prize_type:item.prizeType,amount:item.prizeType==='CASH'?Number(item.amount):null,currency_code:item.prizeType==='CASH'?item.currencyCode:null,sort_order:index,is_active:true}));const result=await request<{prizes:CompetitionSeriesPrize[]}>(`/api/clubs/${clubId}/competition/series/${seriesId}/prizes`,{method:'PUT',body:JSON.stringify({series_revision:seriesRevision,prizes:payload})});setItems(result.prizes);setEditing(false);setFeedback({tone:'success',title:'Premios guardados',message:'La información del circuito quedó actualizada.'});await reload()}catch(error){setFeedback({tone:'error',title:'No pudimos guardar los premios',message:error instanceof Error?error.message:'Intentá nuevamente.'})}finally{setSaving(false)}}
  const notice=feedback?<ActionFeedbackNotice tone={feedback.tone} title={feedback.title} message={feedback.message} onDismiss={()=>setFeedback(null)} autoDismissMs={feedback.tone==='success'?4000:undefined}/>:null
  if(editing)return <section className={styles.panel}>{notice}<header><div><small>PREMIOS DEL CIRCUITO</small><h2>Editar premios</h2></div><button type="button" onClick={add}><Plus size={15}/>Agregar</button></header>{drafts.map((item)=><article className={styles.editor} key={item.id}><button aria-label="Eliminar" type="button" onClick={()=>setDrafts((current)=>current.filter((prize)=>prize.id!==item.id))}><Trash2 size={15}/></button><label>Desde<input type="number" min="1" value={item.positionFrom} onChange={(event)=>patch(item.id,{positionFrom:event.target.value})}/></label><label>Hasta<input type="number" min={item.positionFrom||'1'} value={item.positionTo} onChange={(event)=>patch(item.id,{positionTo:event.target.value})}/></label><label className={styles.wide}>Título<input value={item.title} onChange={(event)=>patch(item.id,{title:event.target.value})}/></label><label>Tipo<select value={item.prizeType} onChange={(event)=>patch(item.id,{prizeType:event.target.value as CompetitionSeriesPrizeType})}>{Object.entries(typeLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>{item.prizeType==='CASH'?<label>Monto<input type="number" min="0" value={item.amount} onChange={(event)=>patch(item.id,{amount:event.target.value})}/></label>:null}</article>)}{!drafts.length?<p className={styles.empty}>Sin premios configurados.</p>:null}<footer><button type="button" onClick={()=>setEditing(false)}>Cancelar</button><button type="button" disabled={saving} onClick={()=>void save()}>{saving?'Guardando…':'Guardar premios'}</button></footer></section>
  return <section className={styles.panel}>{notice}<header><div><small>PREMIOS DEL CIRCUITO</small><h2>{items.length?'Reconocimientos':'Sin premios configurados'}</h2></div>{editable?<button type="button" onClick={items.length?begin:add}>{items.length?'Editar':<><Plus size={15}/>Agregar</>}</button>:<span>Solo lectura</span>}</header>{items.length?<div className={styles.list}>{items.map((item)=><div key={item.id}><Gift size={17}/><span><strong>{position(item.position_from,item.position_to)}</strong><small>{displayAmount(item)||item.title}</small></span></div>)}</div>:<p className={styles.empty}>Este circuito no tiene premios.</p>}</section>
}
