import { NextRequest,NextResponse } from 'next/server'
import { authorizeCompetitionSeries } from '@/features/competition/series/competition-series.auth'
import { readSeriesJson,seriesErrorResponse } from '@/features/competition/series/competition-series.http'
import { getSeriesDetail,rpc } from '@/features/competition/series/competition-series.repository'
import { isUuid,validateSeriesDelete,validateUpdateSeries } from '@/features/competition/series/competition-series.validation'
type Context={params:Promise<{clubId:string;seriesId:string}>}
export async function GET(req:NextRequest,context:Context){const {clubId,seriesId}=await context.params;if(!isUuid(clubId)||!isUuid(seriesId))return NextResponse.json({error:'Identificador inválido.'},{status:400});const auth=await authorizeCompetitionSeries(req,clubId,'read');if(auth.error||!auth.client)return auth.error;try{return NextResponse.json(await getSeriesDetail(auth.client,clubId,seriesId))}catch(error){return seriesErrorResponse(error)}}
export async function PATCH(req:NextRequest,context:Context){const {clubId,seriesId}=await context.params;if(!isUuid(clubId)||!isUuid(seriesId))return NextResponse.json({error:'Identificador inválido.'},{status:400});const auth=await authorizeCompetitionSeries(req,clubId,'write');if(auth.error||!auth.client)return auth.error;const body=await readSeriesJson(req);if('error'in body)return body.error;const value=body.value&&typeof body.value==='object'&&!Array.isArray(body.value)?body.value:{};const validation=validateUpdateSeries({...value,id:seriesId});if('error'in validation)return NextResponse.json({error:validation.error},{status:400});const v=validation.value;try{const series=await rpc(auth.client,'update_competition_series_draft',{p_club_id:clubId,p_series_id:seriesId,p_revision:v.revision,p_name:v.name,p_code:v.code,p_description:v.description,p_starts_on:v.starts_on,p_ends_on:v.ends_on,p_planned_events_count:v.planned_events_count,p_minimum_events_count:v.minimum_events_count,p_is_public:v.is_public});return NextResponse.json({ok:true,series})}catch(error){return seriesErrorResponse(error)}}
export async function DELETE(req:NextRequest,context:Context){const {clubId,seriesId}=await context.params;if(!isUuid(clubId)||!isUuid(seriesId))return NextResponse.json({error:'Identificador inválido.'},{status:400});const auth=await authorizeCompetitionSeries(req,clubId,'delete');if(auth.error||!auth.client)return auth.error;const body=await readSeriesJson(req);if('error'in body)return body.error;const validation=validateSeriesDelete(body.value);if('error'in validation)return NextResponse.json({error:validation.error},{status:400});try{return NextResponse.json(await rpc(auth.client,'delete_competition_series_draft_atomic',{p_club_id:clubId,p_series_id:seriesId,p_revision:validation.value.revision,p_confirmation:validation.value.confirmation}))}catch(error){const coded=error as Error & {code?:string};if(coded.code==='P0001'||coded.message.includes('SERIES_DELETE_BLOCKED'))return NextResponse.json({error:'Este circuito ya tiene actividad vinculada y no puede eliminarse. Conservá su historial mediante el ciclo de vida correspondiente.'},{status:409});return seriesErrorResponse(error)}}
