import type{SupabaseClient}from'@supabase/supabase-js'
import type{Settlement,SettlementDetail}from'./competition-settlement.types'
function failure(operation:string,error:{message:string;code?:string}|null){return Object.assign(new Error(`${operation}: ${error?.message??'error'}`),{code:error?.code})}
export async function settlementRpc<T>(client:SupabaseClient,name:string,args:Record<string,unknown>){const{data,error}=await client.rpc(name,args);if(error)throw failure(name,error);return data as T}
export async function listSettlements(client:SupabaseClient,clubId:string,eventDivisionId:string){const{data,error}=await client.from('competition_event_settlements').select('id,club_id,event_id,event_division_id,homologation_id,homologation_revision,version,revision,status,scoring_mode,series_rule_id,event_tier_id,points_scheme_id,effective_multiplier,calculated_by,calculated_at,submitted_by,submitted_at,approved_by,approved_at,published_by,published_at,rejected_by,rejected_at,rejection_reason,corrected_from_id,superseded_by_id,superseded_at,created_by,created_at,updated_at').eq('club_id',clubId).eq('event_division_id',eventDivisionId).order('version',{ascending:false});if(error)throw failure('list settlements',error);return(data??[])as Settlement[]}
export async function getSettlementDetail(client:SupabaseClient,clubId:string,id:string):Promise<SettlementDetail>{const root=await client.from('competition_event_settlements').select('*').eq('club_id',clubId).eq('id',id).maybeSingle();if(root.error)throw failure('settlement',root.error);if(!root.data)throw Object.assign(new Error('Recurso inexistente.'),{code:'P0002'});const settlement=root.data as Settlement
 const[homologation,division,awards,issues,ledger,preflight]=await Promise.all([
  client.from('competition_event_homologations').select('id,event_id,event_division_id,tournament_id,version,revision,status,result_snapshot,eligibility_snapshot,tournament_snapshot,approved_by,approved_at').eq('club_id',clubId).eq('id',settlement.homologation_id).single(),
  client.from('competition_series_event_divisions').select('id,event_id,series_division_id,series_rule_id,scoring_mode,status,configuration_snapshot').eq('club_id',clubId).eq('id',settlement.event_division_id).single(),
  client.from('competition_event_settlement_awards').select('*').eq('club_id',clubId).eq('settlement_id',id).order('final_position',{ascending:true,nullsFirst:false}),
  client.from('competition_event_settlement_issues').select('*').eq('club_id',clubId).eq('settlement_id',id).order('severity').order('code'),
  client.from('competition_point_transactions').select('id,player_entry_id,club_player_id,points,effective_at,idempotency_key,rule_snapshot,metadata,created_by,created_at').eq('club_id',clubId).eq('source_concept','COMPETITION_EVENT_SETTLEMENT').contains('metadata',{settlement_id:id}),
  client.rpc('get_competition_event_settlement_preflight',{p_club_id:clubId,p_settlement_id:id})])
 for(const result of[homologation,division,awards,issues,ledger,preflight])if(result.error)throw failure('settlement detail',result.error)
 const tournamentId=(homologation.data as{tournament_id:string}).tournament_id;const tournament=await client.from('tournaments').select('id,club_id,name,status,start_date,starts_on,end_date,ends_on,category,gender').eq('club_id',clubId).eq('id',tournamentId).maybeSingle();if(tournament.error)throw failure('settlement tournament',tournament.error)
 return{settlement,homologation:homologation.data as Record<string,unknown>,eventDivision:division.data as Record<string,unknown>,tournament:tournament.data as Record<string,unknown>|null,awards:(awards.data??[])as Record<string,unknown>[],issues:(issues.data??[])as Record<string,unknown>[],ledgerTransactions:(ledger.data??[])as Record<string,unknown>[],preflight:preflight.data as SettlementDetail['preflight']}}
