import{NextRequest,NextResponse}from'next/server'
import{authorizeCompetitionSettlement}from'./competition-settlement.auth'
import{settlementError,readSettlementJson}from'./competition-settlement.http'
import{getSettlementDetail,listSettlements,settlementRpc}from'./competition-settlement.repository'
import{toSettlementAdminDto}from'./competition-settlement.mapper'
import{isUuid,parseKey,parseRevision,record,text}from'./competition-settlement.validation'
type Params={clubId:string;seriesId:string;eventId:string;eventDivisionId:string;settlementId?:string}
const invalid=()=>NextResponse.json({error:'Identificador inválido.'},{status:400})
async function scope(request:NextRequest,p:Params,mode:'read'|'write'){if(![p.clubId,p.seriesId,p.eventId,p.eventDivisionId].every(isUuid)||p.settlementId&&!isUuid(p.settlementId))return{error:invalid(),client:null};const auth=await authorizeCompetitionSettlement(request,p.clubId,mode);if(auth.error||!auth.client)return auth;const division=await auth.client.from('competition_series_event_divisions').select('id,competition_series_events!inner(id,series_id)').eq('club_id',p.clubId).eq('id',p.eventDivisionId).eq('event_id',p.eventId).eq('competition_series_events.series_id',p.seriesId).maybeSingle();if(division.error)throw Object.assign(new Error(division.error.message),{code:division.error.code});if(!division.data)return{...auth,client:null,error:NextResponse.json({error:'Recurso inexistente.'},{status:404})};return auth}
function command(request:NextRequest){const revision=parseRevision(request.headers.get('if-match')),key=parseKey(request.headers.get('idempotency-key'));return revision&&key?{revision,key}:{error:NextResponse.json({error:'If-Match e Idempotency-Key son obligatorios.'},{status:400})}}
export async function settlementsCollection(request:NextRequest,p:Params){try{const auth=await scope(request,p,request.method==='GET'?'read':'write');if(auth.error||!auth.client)return auth.error;if(request.method==='GET')return NextResponse.json({settlements:await listSettlements(auth.client,p.clubId,p.eventDivisionId)});const key=parseKey(request.headers.get('idempotency-key'));if(!key)return NextResponse.json({error:'Idempotency-Key es obligatorio.'},{status:400});return NextResponse.json({settlement:await settlementRpc(auth.client,'create_competition_event_settlement_draft',{p_club_id:p.clubId,p_event_division_id:p.eventDivisionId,p_idempotency_key:key})},{status:201})}catch(error){return settlementError(error)}}
export async function settlementDetail(request:NextRequest,p:Params){try{const auth=await scope(request,p,'read');if(auth.error||!auth.client||!p.settlementId)return auth.error??invalid();return NextResponse.json(toSettlementAdminDto(await getSettlementDetail(auth.client,p.clubId,p.settlementId)))}catch(error){return settlementError(error)}}
export async function settlementPreflight(request:NextRequest,p:Params){try{const auth=await scope(request,p,'read');if(auth.error||!auth.client||!p.settlementId)return auth.error??invalid();return NextResponse.json(await settlementRpc(auth.client,'get_competition_event_settlement_preflight',{p_club_id:p.clubId,p_settlement_id:p.settlementId}))}catch(error){return settlementError(error)}}
export async function settlementCommand(request:NextRequest,p:Params,operation:'calculate'|'submit'|'approve'|'reject'|'publish'|'correction'|'supersede'){try{const auth=await scope(request,p,'write');if(auth.error||!auth.client||!p.settlementId)return auth.error??invalid();const concurrency=command(request);if('error'in concurrency)return concurrency.error;const bodyResult=await readSettlementJson(request);if('error'in bodyResult)return bodyResult.error;const body=record(bodyResult.value);const base={p_club_id:p.clubId,p_settlement_id:p.settlementId,p_revision:concurrency.revision,p_idempotency_key:concurrency.key};let args:Record<string,unknown>=base;if(operation==='reject'||operation==='supersede')args={...base,p_reason:text(body.reason)};const result=await settlementRpc(auth.client,`${operation}_competition_event_settlement`,args);return NextResponse.json({ok:true,result})}catch(error){return settlementError(error)}}
