export const EVENT_TYPES = ['STANDARD','EXHIBITION','FRIENDLY'] as const
export const EVENT_STATUSES = ['DRAFT','SCHEDULED','COMPLETED','CANCELLED'] as const
export const EVENT_SCORING_MODES = ['POINTS','NON_SCORING'] as const
export type EventType=(typeof EVENT_TYPES)[number]
export type EventStatus=(typeof EVENT_STATUSES)[number]
export type EventScoringMode=(typeof EVENT_SCORING_MODES)[number]
export type CompetitionSeriesEvent={id:string;club_id:string;series_id:string;season_id:string;name:string;event_type:EventType;event_number:number|null;sequence:number;status:EventStatus;planned_starts_at:string|null;planned_ends_at:string|null;actual_starts_at:string|null;actual_ends_at:string|null;timezone:string|null;venue_name:string|null;venue_address:string|null;is_public:boolean;revision:number;archived_at:string|null;created_at:string;updated_at:string}
export type CompetitionEventDivision={id:string;club_id:string;event_id:string;series_division_id:string;series_rule_id:string;event_tier_id:string|null;scoring_mode:EventScoringMode|null;points_scheme_override_id:string|null;points_multiplier_override:number|null;status:EventStatus;sort_order:number;is_active:boolean;configuration_snapshot:Record<string,unknown>|null;frozen_at:string|null;revision:number}
export type CompetitionEventDetail={event:CompetitionSeriesEvent;series:Record<string,unknown>;season:Record<string,unknown>;divisions:Array<Record<string,unknown>&{rule:Record<string,unknown>|null;tier:Record<string,unknown>|null;active_tournament_link:Record<string,unknown>|null;link_history:Record<string,unknown>[]}>;schedule_history:Record<string,unknown>[];completeness:Record<string,unknown>}
