import { NextRequest,NextResponse } from 'next/server'
import { authorizeCompetitionEvents } from './competition-events.auth'
import { eventErrorResponse,readEventJson } from './competition-events.http'
import { eventRpc,getEventDetail,getEventDivisionCompletionPreflight,listEvents } from './competition-events.repository'
import { toCompetitionEventAdminDto } from './competition-events.mapper'
import { isUuid,parseIdempotencyKey,parseIfMatch,record,text,validateDivisionConfig,validateEventPatch } from './competition-events.validation'

type Base={clubId:string;seriesId:string;eventId?:string;eventDivisionId?:string}
const invalid=()=>NextResponse.json({error:'Identificador inválido.'},{status:400})
async function auth(req:NextRequest,p:Base,mode:'read'|'write'){
  if(!isUuid(p.clubId)||!isUuid(p.seriesId)||p.eventId&&!isUuid(p.eventId)||p.eventDivisionId&&!isUuid(p.eventDivisionId))return {error:invalid(),client:null,role:null,platform:false}
  let result:Awaited<ReturnType<typeof authorizeCompetitionEvents>>
  try{result=await authorizeCompetitionEvents(req,p.clubId,mode)}catch{return {error:NextResponse.json({error:'No se pudo validar la autorización.'},{status:500}),client:null,role:null,platform:false}}
  if(result.client&&p.eventId){const scoped=await result.client.from('competition_series_events').select('id').eq('club_id',p.clubId).eq('series_id',p.seriesId).eq('id',p.eventId).maybeSingle();if(scoped.error)return {...result,client:null,error:eventErrorResponse(Object.assign(new Error(scoped.error.message),{code:scoped.error.code}))};if(!scoped.data)return {...result,client:null,error:NextResponse.json({error:'Recurso inexistente.'},{status:404})}}
  return result
}
async function json(req:NextRequest){const r=await readEventJson(req);return 'error'in r?r:{value:record(r.value)??{}}}
function concurrency(req:NextRequest,lifecycle=false){const revision=parseIfMatch(req.headers.get('if-match'));const key=lifecycle?parseIdempotencyKey(req.headers.get('idempotency-key')):null;return revision&&(!lifecycle||key)?{revision,key}:{error:NextResponse.json({error:lifecycle?'If-Match e Idempotency-Key son obligatorios.':'If-Match es obligatorio.'},{status:400})}}

export async function eventsCollection(req:NextRequest,p:Base){const a=await auth(req,p,req.method==='GET'?'read':'write');if(a.error||!a.client)return a.error
  try{if(req.method==='GET')return NextResponse.json({events:await listEvents(a.client,p.clubId,p.seriesId)});const b=await json(req);if('error'in b)return b.error;const name=text(b.value.name);if(!name)return NextResponse.json({error:'El nombre es obligatorio.'},{status:400});const event=await eventRpc<Record<string,unknown>>(a.client,'create_competition_series_event',{p_club_id:p.clubId,p_series_id:p.seriesId,p_name:name});return NextResponse.json({ok:true,event,revision:event.revision},{status:201})}catch(e){return eventErrorResponse(e)}}
export async function eventDetail(req:NextRequest,p:Base){const a=await auth(req,p,req.method==='GET'?'read':'write');if(a.error||!a.client||!p.eventId)return a.error??invalid()
  try{if(req.method==='GET')return NextResponse.json(toCompetitionEventAdminDto(await getEventDetail(a.client,p.clubId,p.eventId),a.role,a.platform));const c=concurrency(req);if('error'in c)return c.error;const b=await json(req);if('error'in b)return b.error;const config=validateEventPatch(b.value);if(!config)return NextResponse.json({error:'Configuración inválida.'},{status:400});await eventRpc(a.client,'update_competition_series_event_draft',{p_club_id:p.clubId,p_event_id:p.eventId,p_revision:c.revision,p_config:config});return NextResponse.json(toCompetitionEventAdminDto(await getEventDetail(a.client,p.clubId,p.eventId),a.role,a.platform))}catch(e){return eventErrorResponse(e)}}
export async function divisionsCollection(req:NextRequest,p:Base){const a=await auth(req,p,'write');if(a.error||!a.client||!p.eventId)return a.error??invalid();const c=concurrency(req);if('error'in c)return c.error;const b=await json(req);if('error'in b)return b.error;if(!isUuid(b.value.series_division_id))return invalid();try{await eventRpc(a.client,'add_competition_series_event_division',{p_club_id:p.clubId,p_event_id:p.eventId,p_series_division_id:b.value.series_division_id,p_sort_order:Number(b.value.sort_order??0),p_event_revision:c.revision});return NextResponse.json(toCompetitionEventAdminDto(await getEventDetail(a.client,p.clubId,p.eventId),a.role,a.platform),{status:201})}catch(e){return eventErrorResponse(e)}}
export async function divisionMutation(req:NextRequest,p:Base,action:'CONFIGURE'|'REMOVE'|'RESTORE'|'REFRESH_RULE'){const a=await auth(req,p,'write');if(a.error||!a.client||!p.eventId||!p.eventDivisionId)return a.error??invalid();const c=concurrency(req);if('error'in c)return c.error;const b=await json(req);if('error'in b)return b.error
  try{if(action==='CONFIGURE'){const v=validateDivisionConfig(b.value);if(!v)return NextResponse.json({error:'Configuración inválida.'},{status:400});await eventRpc(a.client,'configure_competition_series_event_division',{p_club_id:p.clubId,p_event_id:p.eventId,p_division_id:p.eventDivisionId,p_event_revision:c.revision,p_scoring_mode:v.scoring_mode,p_event_tier_id:v.event_tier_id??null,p_scheme_override_id:v.points_scheme_override_id??null,p_multiplier_override:v.points_multiplier_override??null})}
    else if(action==='REFRESH_RULE')await eventRpc(a.client,'refresh_competition_series_event_division_rule',{p_club_id:p.clubId,p_event_id:p.eventId,p_division_id:p.eventDivisionId,p_event_revision:c.revision})
    else await eventRpc(a.client,'set_competition_series_event_division_active',{p_club_id:p.clubId,p_event_id:p.eventId,p_division_id:p.eventDivisionId,p_event_revision:c.revision,p_active:action==='RESTORE',p_reason:text(b.value.reason)||null})
    return NextResponse.json(toCompetitionEventAdminDto(await getEventDetail(a.client,p.clubId,p.eventId),a.role,a.platform))}catch(e){return eventErrorResponse(e)}}
export async function lifecycle(req:NextRequest,p:Base,operation:string,division=false){const a=await auth(req,p,'write');if(a.error||!a.client||!p.eventId)return a.error??invalid();try{
  if(req.method==='GET'&&operation==='COMPLETE_DIVISION'&&p.eventDivisionId)return NextResponse.json(await getEventDivisionCompletionPreflight(a.client,p.clubId,p.eventId,p.eventDivisionId))
  const c=concurrency(req,true);if('error'in c)return c.error;const b=await json(req);if('error'in b)return b.error;const payload={...b.value,...(division?{division_id:p.eventDivisionId}:{})}
  if(operation==='COMPLETE_DIVISION'&&p.eventDivisionId){const preflight=await getEventDivisionCompletionPreflight(a.client,p.clubId,p.eventId,p.eventDivisionId);if(!preflight.ready)return NextResponse.json({error:'El torneo todavía no está listo para cerrar la división.',code:'TOURNAMENT_NOT_READY',preflight},{status:409})}
  await eventRpc(a.client,'transition_competition_series_event',{p_club_id:p.clubId,p_event_id:p.eventId,p_revision:c.revision,p_operation:operation,p_key:c.key,p_payload:payload});return NextResponse.json(toCompetitionEventAdminDto(await getEventDetail(a.client,p.clubId,p.eventId),a.role,a.platform))
}catch(e){return eventErrorResponse(e)}}
export async function tournamentLink(req:NextRequest,p:Base){const a=await auth(req,p,'write');if(a.error||!a.client||!p.eventId||!p.eventDivisionId)return a.error??invalid();const c=concurrency(req,true);if('error'in c)return c.error;const b=await json(req);if('error'in b)return b.error
  try{if(req.method==='DELETE')await eventRpc(a.client,'unlink_competition_series_event_tournament',{p_club_id:p.clubId,p_event_id:p.eventId,p_division_id:p.eventDivisionId,p_event_revision:c.revision,p_key:c.key,p_reason:text(b.value.reason)});else{if(!isUuid(b.value.tournament_id))return invalid();await eventRpc(a.client,'link_competition_series_event_tournament',{p_club_id:p.clubId,p_event_id:p.eventId,p_division_id:p.eventDivisionId,p_tournament_id:b.value.tournament_id,p_event_revision:c.revision,p_key:c.key,p_replace:req.method==='PATCH',p_reason:text(b.value.reason)||null})}return NextResponse.json(toCompetitionEventAdminDto(await getEventDetail(a.client,p.clubId,p.eventId),a.role,a.platform))}catch(e){return eventErrorResponse(e)}}
export async function eventReadSubresource(req:NextRequest,p:Base,kind:'completeness'|'history'){const a=await auth(req,p,'read');if(a.error||!a.client||!p.eventId)return a.error??invalid();try{if(kind==='completeness')return NextResponse.json(await eventRpc(a.client,'get_competition_series_event_completeness',{p_club_id:p.clubId,p_event_id:p.eventId}));const d=await getEventDetail(a.client,p.clubId,p.eventId);return NextResponse.json({tournament_links:d.divisions.flatMap((x)=>x.link_history),schedule_history:d.schedule_history})}catch(e){return eventErrorResponse(e)}}
