begin;

create or replace function pg_temp.run_competition_event_settlement_stage5a5_qa()
returns table(qa_status text,qa_detail text) language plpgsql as $$
<<qa>>
declare
  users uuid[]; owner_id uuid; admin_id uuid; operator_id uuid; plan_id uuid; player_id uuid;
  club_a uuid:=gen_random_uuid(); club_b uuid:=gen_random_uuid(); season_id uuid:=gen_random_uuid(); branch_id uuid:=gen_random_uuid(); category_id uuid:=gen_random_uuid(); division_id uuid:=gen_random_uuid();
  series_id uuid:=gen_random_uuid(); series_division_id uuid:=gen_random_uuid(); scheme_id uuid:=gen_random_uuid(); rule_id uuid:=gen_random_uuid(); tier_id uuid:=gen_random_uuid();
  event_points uuid:=gen_random_uuid(); event_non_scoring uuid:=gen_random_uuid(); division_points uuid:=gen_random_uuid(); division_non_scoring uuid:=gen_random_uuid();
  tournament_points uuid:=gen_random_uuid(); tournament_non_scoring uuid:=gen_random_uuid(); category_small smallint;
  cp uuid[]:=array[gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid()];
  entries uuid[]:=array[gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid()];
  teams uuid[]:=array[gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid()];
  ns_teams uuid[]:=array[gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid()];
  homologation_points uuid:=gen_random_uuid(); homologation_non_scoring uuid:=gen_random_uuid(); participant_id uuid;
  settlement_id uuid; settlement_ns uuid; settlement_v2 uuid; settlement_v3 uuid; response jsonb; replay jsonb; preflight jsonb;
  revision integer; event_revision integer; homologation_revision integer; before_count integer; after_count integer; award_total integer; ledger_total integer; i integer; qa_step text:='fixtures';
begin
  if to_regprocedure('public.publish_competition_event_settlement(uuid,uuid,integer,text)') is null then return query select 'FAIL','QA no ejecutable: falta aplicar Stage 5A.5';return;end if;
  select array_agg(x.id order by x.id) into users from(select u.id from auth.users u where u.email is not null and not exists(select 1 from public.platform_admins p where p.user_id=u.id) order by u.id limit 5)x;
  if coalesce(array_length(users,1),0)<5 then return query select 'FAIL','QA no ejecutable: se requieren cinco usuarios auth reales; todos los fixtures de negocio se crean y revierten';return;end if;
  owner_id:=users[1];admin_id:=users[2];operator_id:=users[3];plan_id:=users[4];player_id:=users[5];

  insert into public.clubs(id,name,slug,is_active,status)values(club_a,'QA Settlement A','qa-settlement-'||replace(club_a::text,'-',''),true,'ACTIVE'),(club_b,'QA Settlement B','qa-settlement-'||replace(club_b::text,'-',''),true,'ACTIVE');
  insert into public.club_memberships(club_id,user_id,role,status,approved_at,approved_by)values(club_a,owner_id,'OWNER','APPROVED',now(),owner_id),(club_a,admin_id,'ADMIN','APPROVED',now(),owner_id),(club_a,operator_id,'OPERADOR','APPROVED',now(),owner_id),(club_a,plan_id,'PLANILLERO','APPROVED',now(),owner_id),(club_a,player_id,'PLAYER','APPROVED',now(),owner_id),(club_b,player_id,'OWNER','APPROVED',now(),player_id);
  insert into public.competition_seasons(id,club_id,name,starts_on,ends_on,status,created_by)values(season_id,club_a,'QA Settlement Season','2027-01-01','2027-12-31','ACTIVE',owner_id);
  insert into public.competition_branches(id,club_id,name,slug)values(branch_id,club_a,'QA Settlement','qa-settlement');
  insert into public.competition_categories(id,club_id,name,short_label,slug)values(category_id,club_a,'QA Settlement','QA','qa-settlement');
  insert into public.competition_divisions(id,club_id,season_id,modality,branch_id,category_id)values(division_id,club_a,season_id,'INDIVIDUAL',branch_id,category_id);
  insert into public.points_schemes(id,club_id,name,is_global,is_active,created_by)values(scheme_id,club_a,'QA Settlement',false,true,owner_id);
  insert into public.points_scheme_rules(scheme_id,rule_key,points)values(scheme_id,'CHAMPION',100),(scheme_id,'RUNNER_UP',60),(scheme_id,'SEMIFINALIST',40),(scheme_id,'QUARTERFINALIST',20),(scheme_id,'PARTICIPANT',10);
  perform set_config('selpa.competition_series_write','allowed',true);
  insert into public.competition_series(id,club_id,season_id,name,status,planned_events_count,created_by,activated_by,activated_at)values(series_id,club_a,season_id,'QA Settlement Series','ACTIVE',2,owner_id,owner_id,now());
  insert into public.competition_series_divisions(id,club_id,series_id,division_id,division_snapshot,frozen_at,created_by)values(series_division_id,club_a,series_id,division_id,jsonb_build_object('division_id',division_id,'division_name','QA Settlement','modality','INDIVIDUAL','branch_id',branch_id,'branch_name','QA Settlement','segment_id',null,'segment_name',null,'category_id',category_id,'category_name','QA Settlement','season_id',season_id,'season_name','QA Settlement Season'),now(),owner_id);
  insert into public.competition_series_rules(id,club_id,series_division_id,version,status,points_scheme_id,bonus_rules,penalty_rules,frozen_at,created_by)values(rule_id,club_a,series_division_id,1,'ACTIVE',scheme_id,'{"CHAMPION":3}','{"RUNNER_UP":2}',now(),owner_id);
  insert into public.competition_series_eligibility(club_id,series_rule_id,requires_active_entry,allow_invited_players,invited_points_policy,require_same_division_pair,frozen_at,created_by)values(club_a,rule_id,true,false,'REQUIRE_ENTRY',true,now(),owner_id);
  insert into public.competition_event_tiers(id,club_id,name,code,default_points_scheme_id,points_multiplier,is_active,created_by)values(tier_id,club_a,'QA Settlement Tier','QA-SETTLEMENT',scheme_id,1.5,true,owner_id);
  perform set_config('selpa.competition_event_write','allowed',true);
  insert into public.competition_series_events(id,club_id,series_id,season_id,name,status,sequence,planned_starts_at,planned_ends_at,actual_starts_at,actual_ends_at,timezone,scheduled_by,scheduled_at,completed_by,completed_at,created_by)values(event_points,club_a,series_id,season_id,'QA Points','COMPLETED',1,'2027-06-01','2027-06-02','2027-06-01','2027-06-02','America/Argentina/Buenos_Aires',owner_id,now(),owner_id,now(),owner_id),(event_non_scoring,club_a,series_id,season_id,'QA Non Scoring','COMPLETED',2,'2027-07-01','2027-07-02','2027-07-01','2027-07-02','America/Argentina/Buenos_Aires',owner_id,now(),owner_id,now(),owner_id);
  insert into public.competition_series_event_divisions(id,club_id,event_id,series_division_id,series_rule_id,event_tier_id,scoring_mode,points_scheme_override_id,points_multiplier_override,status,configuration_snapshot,frozen_at,completed_by,completed_at,created_by)values
   (division_points,club_a,event_points,series_division_id,rule_id,tier_id,'POINTS',scheme_id,1.5,'COMPLETED',jsonb_build_object('rule_id',rule_id,'rule_version',1,'tier_id',tier_id,'tier_code','QA-SETTLEMENT','tier_name','QA Settlement Tier','effective_points_scheme_id',scheme_id,'effective_multiplier',1.5,'scoring_mode','POINTS','division',jsonb_build_object('division_id',division_id,'season_id',season_id),'eligibility',jsonb_build_object('requires_active_entry',true),'frozen_at',now()),now(),owner_id,now(),owner_id),
   (division_non_scoring,club_a,event_non_scoring,series_division_id,rule_id,null,'NON_SCORING',null,null,'COMPLETED',jsonb_build_object('rule_id',rule_id,'rule_version',1,'effective_multiplier',1,'scoring_mode','NON_SCORING','division',jsonb_build_object('division_id',division_id,'season_id',season_id),'eligibility',jsonb_build_object('requires_active_entry',true),'frozen_at',now()),now(),owner_id,now(),owner_id);
  select c.id::smallint into category_small from generate_series(32000,32767)c(id)where not exists(select 1 from public.categories x where x.id=c.id)order by c.id limit 1;
  insert into public.categories(id,name)values(category_small,'QA Settlement '||category_small);
  insert into public.tournaments(id,club_id,name,type,start_date,end_date,status,category_id,category,category_rule,fixed_category_id,gender,tournament_type)values(tournament_points,club_a,'QA Settlement Points','OPEN','2027-06-01','2027-06-02','FINISHED',category_small,6,'FIXED_CATEGORY',category_small,'MIXED','OPEN'),(tournament_non_scoring,club_a,'QA Settlement NS','OPEN','2027-07-01','2027-07-02','FINISHED',category_small,6,'FIXED_CATEGORY',category_small,'MIXED','OPEN');
  insert into public.competition_series_event_tournament_links(club_id,event_division_id,tournament_id,status,linked_by)values(club_a,division_points,tournament_points,'ACTIVE',owner_id),(club_a,division_non_scoring,tournament_non_scoring,'ACTIVE',owner_id);
  insert into public.club_players(id,club_id,user_id,display_name,category,gender,approved_at,approved_by)values(cp[1],club_a,owner_id,'QA Champion',6,'M',now(),owner_id),(cp[2],club_a,admin_id,'QA Runner',6,'F',now(),owner_id),(cp[3],club_a,operator_id,'QA Semi',6,'M',now(),owner_id),(cp[4],club_a,plan_id,'QA Quarter',6,'F',now(),owner_id),(cp[5],club_a,player_id,'QA Participant',6,'M',now(),owner_id);
  for i in 1..5 loop insert into public.competition_player_entries(id,club_id,division_id,club_player_id,status,assigned_by)values(entries[i],club_a,division_id,cp[i],'ACTIVE',owner_id); end loop;
  for i in 1..5 loop insert into public.tournament_teams(id,tournament_id,club_id,player1_user_id,player2_user_id,created_by)values(teams[i],tournament_points,club_a,users[i],users[case when i=5 then 1 else i+1 end],owner_id),(ns_teams[i],tournament_non_scoring,club_a,users[i],users[case when i=5 then 1 else i+1 end],owner_id); end loop;

  perform set_config('selpa.competition_homologation_write','allowed',true);
  insert into public.competition_event_homologations(id,club_id,event_id,event_division_id,tournament_id,version,revision,status,result_snapshot,eligibility_snapshot,tournament_snapshot,submitted_by,submitted_at,approved_by,approved_at,created_by)values
   (homologation_points,club_a,event_points,division_points,tournament_points,1,1,'APPROVED',jsonb_build_object('source','QA','revision','1'),jsonb_build_object('frozen',true),jsonb_build_object('tournament_id',tournament_points),owner_id,now(),owner_id,now(),owner_id),
   (homologation_non_scoring,club_a,event_non_scoring,division_non_scoring,tournament_non_scoring,1,1,'APPROVED',jsonb_build_object('source','QA','revision','1'),jsonb_build_object('frozen',true),jsonb_build_object('tournament_id',tournament_non_scoring),owner_id,now(),owner_id,now(),owner_id);
  for i in 1..5 loop
    insert into public.competition_event_homologation_results(club_id,homologation_id,tournament_team_id,final_position,result_role,result_snapshot)values(club_a,homologation_points,teams[i],i,(array['CHAMPION','RUNNER_UP','SEMIFINALIST','QUARTERFINALIST','PARTICIPANT'])[i],jsonb_build_object('position',i)),(club_a,homologation_non_scoring,ns_teams[i],i,(array['CHAMPION','RUNNER_UP','SEMIFINALIST','QUARTERFINALIST','PARTICIPANT'])[i],jsonb_build_object('position',i));
    participant_id:=gen_random_uuid(); insert into public.competition_event_homologation_participants(id,club_id,homologation_id,player_id,club_player_id,competition_player_entry_id,tournament_team_id,participation_status,scoring_eligibility_status,exclusion_code,exclusion_reason,final_position,result_role,participant_snapshot)values(participant_id,club_a,homologation_points,users[i],cp[i],case when i=5 then null else entries[i] end,teams[i],'FINISHED',case when i=5 then 'NON_SCORING' else 'ELIGIBLE' end,case when i=5 then 'INVITED_NON_SCORING' end,case when i=5 then 'Participante QA sin adjudicación.' end,i,(array['CHAMPION','RUNNER_UP','SEMIFINALIST','QUARTERFINALIST','PARTICIPANT'])[i],jsonb_build_object('player_id',users[i],'display_name','QA Player '||i));
    insert into public.competition_event_homologation_participants(club_id,homologation_id,player_id,club_player_id,competition_player_entry_id,tournament_team_id,participation_status,scoring_eligibility_status,exclusion_code,exclusion_reason,final_position,result_role,participant_snapshot)values(club_a,homologation_non_scoring,users[i],cp[i],entries[i],ns_teams[i],'FINISHED','ELIGIBLE',null,null,i,(array['CHAMPION','RUNNER_UP','SEMIFINALIST','QUARTERFINALIST','PARTICIPANT'])[i],jsonb_build_object('player_id',users[i],'display_name','QA NS Player '||i));
  end loop;

  select event_row.revision into event_revision from public.competition_series_events event_row where event_row.id=event_points; select homologation_row.revision into homologation_revision from public.competition_event_homologations homologation_row where homologation_row.id=homologation_points;
  qa_step:='points owner';perform set_config('request.jwt.claim.sub',owner_id::text,true);perform set_config('request.jwt.claim.role','authenticated',true);set local role authenticated;
  response:=public.create_competition_event_settlement_draft(club_a,division_points,'qa-settlement-create-0001');settlement_id:=(response->>'settlement_id')::uuid;revision:=(response->>'revision')::integer;
  if (response->>'status')<>'DRAFT' or (response->>'version')::integer<>1 then raise exception 'DRAFT/version 1 inválido';end if;
  begin perform public.calculate_competition_event_settlement(club_a,settlement_id,revision+1,'qa-settlement-stale-0001');raise exception 'Stale calculate aceptado';exception when serialization_failure then null;end;
  response:=public.calculate_competition_event_settlement(club_a,settlement_id,revision,'qa-settlement-calc-0001');replay:=public.calculate_competition_event_settlement(club_a,settlement_id,revision,'qa-settlement-calc-0001');if replay is distinct from response then raise exception 'Replay calculate inválido';end if;revision:=(response->>'revision')::integer;
  if (select count(*) from public.competition_event_settlement_awards award where award.settlement_id=qa.settlement_id)<>5 then raise exception 'Awards incompletos';end if;
  if (select award.total_points from public.competition_event_settlement_awards award where award.settlement_id=qa.settlement_id and award.result_code='CHAMPION')<>155 then raise exception 'Campeón/bonus/multiplier/ROUND inválido';end if;
  if (select award.total_points from public.competition_event_settlement_awards award where award.settlement_id=qa.settlement_id and award.result_code='RUNNER_UP')<>87 then raise exception 'Subcampeón/penalty inválido';end if;
  if (select award.total_points from public.competition_event_settlement_awards award where award.settlement_id=qa.settlement_id and award.result_code='SEMIFINALIST')<>60 or (select award.total_points from public.competition_event_settlement_awards award where award.settlement_id=qa.settlement_id and award.result_code='QUARTERFINALIST')<>30 then raise exception 'Semifinal/cuartos inválidos';end if;
  if (select award.total_points from public.competition_event_settlement_awards award where award.settlement_id=qa.settlement_id and award.result_code='PARTICIPANT')<>0 then raise exception 'Award no elegible no quedó en cero';end if;
  preflight:=public.get_competition_event_settlement_preflight(club_a,settlement_id);if jsonb_array_length(preflight->'blockers')<>0 or jsonb_array_length(preflight->'warnings')=0 then raise exception 'Preflight blockers/warnings inválido';end if;
  response:=public.submit_competition_event_settlement(club_a,settlement_id,revision,'qa-settlement-submit-001');revision:=(response->>'revision')::integer;
  select count(*) into before_count from public.competition_point_transactions point_tx where point_tx.metadata->>'settlement_id'=settlement_id::text;
  response:=public.approve_competition_event_settlement(club_a,settlement_id,revision,'qa-settlement-approve-01');revision:=(response->>'revision')::integer;
  if (select count(*) from public.competition_point_transactions point_tx where point_tx.metadata->>'settlement_id'=settlement_id::text)<>before_count then raise exception 'Approve escribió ledger';end if;
  response:=public.publish_competition_event_settlement(club_a,settlement_id,revision,'qa-settlement-publish-01');replay:=public.publish_competition_event_settlement(club_a,settlement_id,revision,'qa-settlement-publish-01');if replay is distinct from response then raise exception 'Replay publish inválido';end if;
  select count(*),coalesce(sum(point_tx.points),0) into after_count,ledger_total from public.competition_point_transactions point_tx where point_tx.metadata->>'settlement_id'=settlement_id::text;select sum(award.total_points) into award_total from public.competition_event_settlement_awards award where award.settlement_id=qa.settlement_id and award.total_points<>0 and award.scoring_eligibility_status='ELIGIBLE';
  if after_count<>4 or ledger_total<>award_total or ledger_total<>332 then raise exception 'Publicación ledger no coincide con awards';end if;
  if exists(select 1 from public.competition_point_transactions point_tx where point_tx.metadata->>'settlement_id'=settlement_id::text and (point_tx.transaction_type<>'TOURNAMENT_RESULT' or point_tx.source_type<>'TOURNAMENT' or point_tx.idempotency_key not like 'settlement:%:award:%' or point_tx.rule_snapshot->>'rounding'<>'ROUND_NEAREST_INTEGER'))then raise exception 'Contrato/metadata ledger inválido';end if;
  begin update public.competition_event_settlements as settlement_row set status='DRAFT' where settlement_row.id=settlement_id;raise exception 'PUBLISHED mutable';exception when check_violation or insufficient_privilege then null;end;

  qa_step:='non-scoring operator';reset role;perform set_config('request.jwt.claim.sub',operator_id::text,true);set local role authenticated;
  response:=public.create_competition_event_settlement_draft(club_a,division_non_scoring,'qa-settlement-ns-create1');settlement_ns:=(response->>'settlement_id')::uuid;revision:=(response->>'revision')::integer;
  response:=public.calculate_competition_event_settlement(club_a,settlement_ns,revision,'qa-settlement-ns-calc01');revision:=(response->>'revision')::integer;if exists(select 1 from public.competition_event_settlement_awards award where award.settlement_id=settlement_ns and award.total_points<>0)then raise exception 'NON_SCORING produjo puntos';end if;
  response:=public.submit_competition_event_settlement(club_a,settlement_ns,revision,'qa-settlement-ns-submit');revision:=(response->>'revision')::integer;
  begin perform public.approve_competition_event_settlement(club_a,settlement_ns,revision,'qa-operator-approve-001');raise exception 'OPERADOR aprobó';exception when insufficient_privilege then null;end;
  reset role;perform set_config('request.jwt.claim.sub',admin_id::text,true);set local role authenticated;response:=public.approve_competition_event_settlement(club_a,settlement_ns,revision,'qa-admin-approve-ns01');revision:=(response->>'revision')::integer;response:=public.publish_competition_event_settlement(club_a,settlement_ns,revision,'qa-admin-publish-ns01');
  if exists(select 1 from public.competition_point_transactions point_tx where point_tx.metadata->>'settlement_id'=settlement_ns::text)or(response->>'status')<>'PUBLISHED'then raise exception 'NON_SCORING publish inválido';end if;

  qa_step:='versions owner';reset role;perform set_config('request.jwt.claim.sub',owner_id::text,true);set local role authenticated;
  response:=public.create_competition_event_settlement_draft(club_a,division_points,'qa-settlement-create-v2-1');settlement_v2:=(response->>'settlement_id')::uuid;revision:=(response->>'revision')::integer;response:=public.calculate_competition_event_settlement(club_a,settlement_v2,revision,'qa-settlement-calc-v2-01');revision:=(response->>'revision')::integer;
  begin perform public.publish_competition_event_settlement(club_a,settlement_v2,revision,'qa-publish-unapproved-001');raise exception 'Publish sin approve aceptado';exception when check_violation then null;end;
  response:=public.submit_competition_event_settlement(club_a,settlement_v2,revision,'qa-settlement-submit-v201');revision:=(response->>'revision')::integer;
  begin perform public.reject_competition_event_settlement(club_a,settlement_v2,revision,'qa-reject-empty-00001','');raise exception 'Reject sin motivo aceptado';exception when invalid_parameter_value then null;end;
  response:=public.reject_competition_event_settlement(club_a,settlement_v2,revision,'qa-settlement-reject-v201','Corrección QA');revision:=(response->>'revision')::integer;
  response:=public.create_competition_event_settlement_correction(club_a,settlement_v2,revision,'qa-settlement-correct-v301');settlement_v3:=(response->>'settlement_id')::uuid;
  if (response->>'version')::integer<>3 or (select settlement_row.corrected_from_id from public.competition_event_settlements settlement_row where settlement_row.id=settlement_v3)<>settlement_v2 then raise exception 'Correction/version 3 inválida';end if;
  response:=public.supersede_competition_event_settlement(club_a,settlement_v3,(response->>'revision')::integer,'qa-settlement-super-v301','Descartado QA');if(response->>'status')<>'SUPERSEDED'then raise exception 'Supersede inválido';end if;
  begin perform public.supersede_competition_event_settlement(club_a,settlement_id,(select settlement_row.revision from public.competition_event_settlements settlement_row where settlement_row.id=settlement_id),'qa-super-published-001','No permitido');raise exception 'PUBLISHED superseded';exception when check_violation then null;end;

  qa_step:='roles planillero';reset role;perform set_config('request.jwt.claim.sub',plan_id::text,true);set local role authenticated;perform public.get_competition_event_settlement_preflight(club_a,settlement_id);
  begin perform public.create_competition_event_settlement_draft(club_a,division_points,'qa-plan-create-000001');raise exception 'PLANILLERO creó settlement';exception when insufficient_privilege then null;end;
  begin update public.competition_event_settlements as settlement_row set updated_at=now() where settlement_row.id=settlement_id;raise exception 'DML directo settlements permitido';exception when insufficient_privilege then null;end;
  begin delete from public.competition_event_settlement_awards award where award.settlement_id=qa.settlement_id;raise exception 'DML directo awards permitido';exception when insufficient_privilege then null;end;
  qa_step:='roles player';reset role;perform set_config('request.jwt.claim.sub',player_id::text,true);set local role authenticated;
  begin perform public.get_competition_event_settlement_preflight(club_a,settlement_id);raise exception 'PLAYER leyó settlement';exception when no_data_found or insufficient_privilege then null;end;
  begin perform public.get_competition_event_settlement_preflight(club_b,settlement_id);raise exception 'Cross-club visible';exception when no_data_found or insufficient_privilege then null;end;
  qa_step:='platform admin';reset role;insert into public.platform_admins(user_id)values(player_id);perform set_config('request.jwt.claim.sub',player_id::text,true);set local role authenticated;perform public.get_competition_event_settlement_preflight(club_a,settlement_id);
  reset role;delete from public.platform_admins where user_id=player_id;perform set_config('request.jwt.claim.sub','',true);perform set_config('request.jwt.claim.role','anon',true);set local role anon;
  begin perform public.get_competition_event_settlement_preflight(club_a,settlement_id);raise exception 'Anon leyó settlement';exception when invalid_authorization_specification or insufficient_privilege then null;end;
  reset role;
  if (select event_row.revision from public.competition_series_events event_row where event_row.id=event_points)<>event_revision or(select homologation_row.revision from public.competition_event_homologations homologation_row where homologation_row.id=homologation_points)<>homologation_revision then raise exception 'Settlement modificó event/homologation revision';end if;
  return query select 'PASS','Stage 5A.5 QA transaccional: cálculo, awards, preflight, lifecycle, revisiones, idempotencia secuencial, publicación atómica en ledger, NON_SCORING, roles, RLS y aislamiento';
exception when others then reset role;return query select 'FAIL',qa_step||' | '||sqlerrm;
end $$;

select qa_status||' | '||qa_detail as result from pg_temp.run_competition_event_settlement_stage5a5_qa();
rollback;
