import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdir} from 'node:fs/promises'
import {fileURLToPath} from 'node:url'
import {PLAYER,CLUB,CLUB_PLAYER,id,QA_TOKEN} from './block1-fixture.mjs'
const require=createRequire(process.env.SELPA_PLAYWRIGHT_PACKAGE ?? 'C:/Users/CESCOBAR/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/package.json')
const {chromium}=require('playwright')
const base='http://127.0.0.1:3011'
const profile=`/jugadores/${PLAYER}?clubId=${CLUB}`
const browser=await chromium.launch({headless:true,executablePath:process.env.SELPA_QA_BROWSER ?? 'C:/Program Files/Google/Chrome/Application/chrome.exe'})
const folder=fileURLToPath(new URL('../../../../output/block1-qa/screens/',import.meta.url));await mkdir(folder,{recursive:true})
const apiChecks=[]
async function api(path,authorization) {
  const res=await fetch(base+path,{headers:authorization?{Authorization:'Bearer '+authorization}:{}})
  const text=await res.text();return {status:res.status,data:JSON.parse(text),text,bytes:Buffer.byteLength(text),cache:res.headers.get('cache-control')}
}
try {
  const summary=await api(`/api/players/${PLAYER}/career?clubId=${CLUB}`)
  assert.equal(summary.status,200);assert.equal(summary.data.summary.standing.position,5);assert.equal(summary.data.summary.stats.titles,2)
  assert.doesNotMatch(summary.text,/private-6|PRIVATE_PHONE|birth_date|phone_e164|email|club_role|finance/)
  apiChecks.push({section:'summary',status:summary.status,bytes:summary.bytes})
  for(const section of ['history','recent']) {
    const r=await api(`/api/players/${PLAYER}/career?clubId=${CLUB}&section=${section}`)
    assert.equal(r.status,200);assert.equal(r.data.rows.length,4);assert.doesNotMatch(r.text,/private-6|PRIVATE_PHONE|email|birth_date/)
    apiChecks.push({section,status:r.status,bytes:r.bytes})
  }
  assert.equal((await api('/api/player/my-ranking?clubId='+CLUB)).status,401)
  assert.equal((await api('/api/player/my-ranking?clubId='+CLUB,'invalid')).status,401)
  const mine=await api('/api/player/my-ranking?clubId='+CLUB,QA_TOKEN)
  assert.equal(mine.status,200);assert.ok(mine.data.individual.length<=7);assert.match(mine.cache,/private/)
  assert.equal(mine.data.individual.find(r=>r.user_id===PLAYER).position,5)
  apiChecks.push({section:'my-ranking',status:mine.status,bytes:mine.bytes,rows:mine.data.individual.length})
  const own=await api(`/api/clubs/${CLUB}/players/${CLUB_PLAYER}/profile`,QA_TOKEN)
  assert.equal(own.status,200);assert.equal(own.data.visibility,'private');assert.match(own.cache,/private/)
  assert.equal((await api(`/api/clubs/${CLUB}/players/${id(2010)}/profile`,QA_TOKEN)).status,403)
  assert.equal((await api(`/api/players/${id(1002)}/career`)).status,404)
  const context=await browser.newContext({permissions:['clipboard-read','clipboard-write']})
  const blocked=[],errors=[]
  await context.route('**/*',async route=>{
    const url=new URL(route.request().url())
    if(!['127.0.0.1','localhost'].includes(url.hostname)){blocked.push(url.hostname);return route.abort()}
    return route.continue()
  })
  const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message))
  const viewportChecks=[]
  for(const width of [320,375,390,430,768,1280]) {
    await page.setViewportSize({width,height:844})
    const res=await page.goto(base+profile,{waitUntil:'networkidle'});assert.equal(res.status(),200)
    await page.getByRole('tab',{name:'Resumen',exact:true}).waitFor()
    await page.getByText('Posición en categoría',{exact:true}).waitFor()
    await page.waitForFunction(()=>document.querySelector('main')?.textContent.includes('#5'))
    assert.equal(await page.getByRole('link',{name:'Editar fotos, datos y pareja'}).count(),0)
    assert.ok(!page.url().includes('/login'))
    const measure=await page.evaluate(()=>({width:innerWidth,document:document.documentElement.scrollWidth,main:document.querySelector('main main')?.getBoundingClientRect().toJSON(),h1:document.querySelector('h1')?.getBoundingClientRect().toJSON()}))
    assert.ok(measure.document<=width,JSON.stringify(measure))
    if(width<=430){assert.equal(measure.main.x,8);assert.equal(measure.main.width,width-16)}
    viewportChecks.push({route:'public-career',...measure})
    await page.screenshot({path:folder+`career-${width}.png`,fullPage:true})
    await page.getByRole('tab',{name:'Torneos',exact:true}).click()
    await page.getByRole('link',{name:'Torneo QA 1',exact:true}).waitFor()
    assert.ok((await page.getByRole('tabpanel').innerText()).includes('5ª categoría'))
    assert.ok((await page.getByRole('tabpanel').innerText()).includes('Pareja histórica'))
    await page.getByRole('tab',{name:'Estadísticas',exact:true}).click()
    assert.ok((await page.getByRole('tabpanel').innerText()).includes('50%'))
    await page.goto(base+`/ranking?clubId=${CLUB}&q=Nombre%20quinto`,{waitUntil:'networkidle'})
    const row=page.locator('.rankingCard');assert.equal(await row.count(),1);assert.ok((await row.innerText()).includes('#5'))
    assert.ok(await page.getByRole('link',{name:/Nombre quinto/}).count())
    const rankingWidth=await page.evaluate(()=>document.documentElement.scrollWidth)
    assert.ok(rankingWidth<=width,`ranking overflow ${width}: ${rankingWidth}`)
    if(width<=430) assert.equal(await page.locator('main main').evaluate(el=>el.getBoundingClientRect().x),8)
    viewportChecks.push({route:'public-ranking',width,document:rankingWidth})
    await page.screenshot({path:folder+`ranking-${width}.png`,fullPage:true})
    const rankingUrl=new URL(page.url())
    for(const key of ['clubId','season','division','category','gender','modality']) assert.ok(rankingUrl.searchParams.has(key),key+' context missing')
    await page.goto(base+`/clubs/${CLUB}`,{waitUntil:'networkidle'})
    const preview=page.locator('.clubPublicRankingBranches')
    assert.ok(await preview.count());assert.doesNotMatch(await preview.innerText(),/Vista demo|Lucía Galarza|Joaquín Pereyra|por confirmar/)
    assert.ok((await preview.innerText()).includes('9900'))
    assert.ok(await page.locator('.clubPublicRankingBranches.is-single').count())
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))
    viewportChecks.push({route:'public-club',width,document:await page.evaluate(()=>document.documentElement.scrollWidth)})
    await page.screenshot({path:folder+`club-${width}.png`,fullPage:true})
  }
  const html=await (await fetch(base+profile)).text()
  assert.doesNotMatch(html,/private-6@|PRIVATE_PHONE|birth_date|phone_e164|Editar fotos, datos y pareja/)
  assert.match(html,/Carrera de pádel|Carrera de pád/)
  await page.goto(base+`/ranking?clubId=${CLUB}&modality=PAIRS`,{waitUntil:'networkidle'})
  assert.equal(new URL(page.url()).searchParams.get('division'),id(21))
  assert.match(await page.locator('.pairRankingCard').innerText(),/10/)
  await page.goto(base+`/ranking/caballeros?clubId=${CLUB}&q=Nombre%20quinto`,{waitUntil:'networkidle'})
  assert.match(await page.locator('.rankingCard').innerText(),/#5/)
  await page.goto(base+`/ranking/damas?clubId=${CLUB}`,{waitUntil:'networkidle'})
  assert.equal(await page.locator('.rankingCard').count(),0)
  await page.goto(base+profile,{waitUntil:'networkidle'})
  await page.evaluate(()=>Object.defineProperty(navigator,'share',{value:undefined,configurable:true}))
  await page.getByRole('button',{name:'Compartir perfil público'}).click()
  await page.getByRole('status').filter({hasText:'Enlace público copiado'}).waitFor()
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),base+profile)
  await fetch('http://127.0.0.1:45432/qa/unavailable?value=true')
  await page.setViewportSize({width:390,height:844})
  await page.goto(base+profile,{waitUntil:'networkidle'})
  await page.getByText('Carrera pendiente de lectura',{exact:true}).waitFor()
  assert.ok(await page.getByRole('heading',{name:/Nombre quinto/}).count())
  await page.screenshot({path:folder+'career-unavailable-390.png',fullPage:true})
  await fetch('http://127.0.0.1:45432/qa/unavailable?value=false')
  await context.addInitScript(({token,user})=>localStorage.setItem('sb-127-auth-token',JSON.stringify({access_token:token,refresh_token:'qa-refresh',expires_at:4102444800,expires_in:3600,token_type:'bearer',user})),{token:QA_TOKEN,user:{id:PLAYER,email:'private-6@invalid.test',aud:'authenticated',role:'authenticated',user_metadata:{},app_metadata:{},created_at:'2026-01-01T00:00:00Z'}})
  // Auxiliary navbar counts are outside Block 1; no fake data enters the app's sports DTOs.
  await page.route('**/api/inbox-summary',route=>route.fulfill({json:{notifications:0,messages:0,unread:0}}))
  await page.goto(base+'/player/carrera/'+CLUB_PLAYER,{waitUntil:'networkidle'})
  await page.getByRole('heading',{name:'Mi carrera',exact:true}).waitFor()
  await page.getByRole('link',{name:'Editar fotos, datos y pareja'}).waitFor()
  await page.screenshot({path:folder+'own-career-390.png',fullPage:true})
  await page.getByRole('link',{name:'Editar fotos, datos y pareja'}).click()
  await page.waitForURL('**/player/carrera/**/editar?own=1')
  await page.getByRole('heading',{name:/Nombre quinto/}).waitFor()
  assert.equal(await page.getByText('Ficha administrativa',{exact:true}).count(),0)
  assert.equal(await page.getByRole('link',{name:'Gestionar equipo'}).count(),0)
  assert.ok(await page.locator('#player-profile-avatar-file').count())
  assert.ok(await page.locator('#player-profile-cover-file').count())
  await page.screenshot({path:folder+'own-editor-390.png',fullPage:true})
  await page.goto(base+'/player/'+CLUB,{waitUntil:'networkidle'})
  await page.waitForFunction(()=>document.querySelector('.playerClubStats')?.textContent.includes('#5'))
  assert.match(await page.locator('.playerClubStats').innerText(),/9410 pts/)
  assert.match(await page.locator('.playerClubStats').innerText(),/4/)
  await page.getByRole('button',{name:'Ver últimos resultados confirmados'}).click()
  await page.getByRole('link',{name:/Torneo QA/}).first().waitFor()
  await page.screenshot({path:folder+'club-home-390.png',fullPage:true})
  await page.goto(base+'/player/ranking',{waitUntil:'networkidle'})
  await page.getByText('Posición actual',{exact:true}).waitFor()
  assert.ok((await page.locator('.playerRankShell').innerText()).includes('#5'))
  await page.screenshot({path:folder+'my-ranking-390.png',fullPage:true})
  assert.match(await page.locator('.playerRankContextRow.is-me').innerText(),/Vos/)
  await page.goto(base+'/player/ranking/club/todos?categoria=6&q=Nombre%20quinto',{waitUntil:'networkidle'})
  await page.waitForURL('**/ranking?**')
  assert.match(await page.locator('.rankingCard').innerText(),/#5/)
  await page.goto(base+'/player',{waitUntil:'networkidle'})
  await page.waitForFunction(()=>document.querySelector('.playerHome')?.textContent.includes('9410') || document.body.textContent.includes('9410 pts'))
  await page.screenshot({path:folder+'player-home-390.png',fullPage:true})
  await context.close()
  console.log(JSON.stringify({apiChecks,viewportChecks,errors,blockedExternal:blocked,screens:folder},null,2))
  assert.equal(errors.length,0)
} finally {
  await fetch('http://127.0.0.1:45432/qa/unavailable?value=false').catch(()=>{})
  await browser.close()
}
