import { NextRequest,NextResponse } from 'next/server'
import { authorizeCompetitionSeries } from '@/features/competition/series/competition-series.auth'
import { readSeriesJson,seriesErrorResponse } from '@/features/competition/series/competition-series.http'
import { assertSeriesDivision,assertSeriesRule,getSeriesRevision,rpc } from '@/features/competition/series/competition-series.repository'
import { isUuid,validateRuleCreate,validateRuleUpdate } from '@/features/competition/series/competition-series.validation'
type Context={params:Promise<{clubId:string;seriesId:string}>}
function record(value:unknown){return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:null}
export async function GET(req:NextRequest,context:Context){const {clubId,seriesId}=await context.params;if(!isUuid(clubId)||!isUuid(seriesId))return NextResponse.json({error:'Identificador inválido.'},{status:400});const auth=await authorizeCompetitionSeries(req,clubId,'read');if(auth.error||!auth.client)return auth.error;const {data:links,error:linkError}=await auth.client.from('competition_series_divisions').select('id').eq('club_id',clubId).eq('series_id',seriesId);if(linkError)return seriesErrorResponse(Object.assign(new Error(linkError.message),{code:linkError.code}));const ids=(links??[]).map((item)=>item.id);if(!ids.length)return NextResponse.json({rules:[]});const {data,error}=await auth.client.from('competition_series_rules').select('*,competition_series_eligibility(*)').in('series_division_id',ids).order('version',{ascending:false});if(error)return seriesErrorResponse(Object.assign(new Error(error.message),{code:error.code}));return NextResponse.json({rules:data??[]})}
export async function POST(req:NextRequest,context:Context){const {clubId,seriesId}=await context.params;if(!isUuid(clubId)||!isUuid(seriesId))return NextResponse.json({error:'Identificador inválido.'},{status:400});const auth=await authorizeCompetitionSeries(req,clubId,'write');if(auth.error||!auth.client)return auth.error;const body=await readSeriesJson(req);if('error'in body)return body.error;const validation=validateRuleCreate(body.value);if('error'in validation)return NextResponse.json({error:validation.error},{status:400});try{await assertSeriesDivision(auth.client,clubId,seriesId,validation.value.seriesDivisionId);const rule=await rpc(auth.client,'create_competition_series_rule_version',{p_club_id:clubId,p_series_id:seriesId,p_series_revision:validation.value.seriesRevision,p_series_division_id:validation.value.seriesDivisionId,p_points_scheme_id:validation.value.pointsSchemeId,p_clone_rule_id:validation.value.cloneRuleId});return NextResponse.json({ok:true,rule,revision:await getSeriesRevision(auth.client,clubId,seriesId)},{status:201})}catch(error){return seriesErrorResponse(error)}}
export async function PATCH(req:NextRequest,context:Context){const {clubId,seriesId}=await context.params;if(!isUuid(clubId)||!isUuid(seriesId))return NextResponse.json({error:'Identificador inválido.'},{status:400});const auth=await authorizeCompetitionSeries(req,clubId,'write');if(auth.error||!auth.client)return auth.error;const parsed=await readSeriesJson(req);if('error'in parsed)return parsed.error;const body=record(parsed.value);if(body?.action==='ACTIVATE'){const id=body.id,ruleRevision=Number(body.revision),seriesRevision=Number(body.series_revision);if(!isUuid(id)||!Number.isInteger(ruleRevision)||ruleRevision<1||!Number.isInteger(seriesRevision)||seriesRevision<1)return NextResponse.json({error:'Regla o revisión inválida.'},{status:400});try{await assertSeriesRule(auth.client,clubId,seriesId,id);const rule=await rpc(auth.client,'activate_competition_series_rule_version',{p_club_id:clubId,p_series_id:seriesId,p_series_revision:seriesRevision,p_rule_id:id,p_rule_revision:ruleRevision});return NextResponse.json({ok:true,rule,revision:await getSeriesRevision(auth.client,clubId,seriesId)})}catch(error){return seriesErrorResponse(error)}}const validation=validateRuleUpdate(body);if('error'in validation)return NextResponse.json({error:validation.error},{status:400});try{await assertSeriesRule(auth.client,clubId,seriesId,validation.value.id);const rule=await rpc(auth.client,'update_competition_series_rule_draft',{p_club_id:clubId,p_series_id:seriesId,p_series_revision:validation.value.seriesRevision,p_rule_id:validation.value.id,p_rule_revision:validation.value.revision,p_config:validation.value.config});return NextResponse.json({ok:true,rule,revision:await getSeriesRevision(auth.client,clubId,seriesId)})}catch(error){return seriesErrorResponse(error)}}
export async function DELETE(req:NextRequest,context:Context){const {clubId,seriesId}=await context.params;if(!isUuid(clubId)||!isUuid(seriesId))return NextResponse.json({error:'Identificador inválido.'},{status:400});const auth=await authorizeCompetitionSeries(req,clubId,'write');if(auth.error||!auth.client)return auth.error;const parsed=await readSeriesJson(req);if('error'in parsed)return parsed.error;const body=record(parsed.value),id=body?.id,ruleRevision=Number(body?.revision),seriesRevision=Number(body?.series_revision);if(!isUuid(id)||!Number.isInteger(ruleRevision)||ruleRevision<1||!Number.isInteger(seriesRevision)||seriesRevision<1)return NextResponse.json({error:'Regla o revisión inválida.'},{status:400});try{await assertSeriesRule(auth.client,clubId,seriesId,id);const deletedId=await rpc(auth.client,'delete_competition_series_rule_draft',{p_club_id:clubId,p_series_id:seriesId,p_series_revision:seriesRevision,p_rule_id:id,p_rule_revision:ruleRevision});return NextResponse.json({ok:true,id:deletedId,revision:await getSeriesRevision(auth.client,clubId,seriesId)})}catch(error){return seriesErrorResponse(error)}}
